version: "3.8"

services: 
  backend_javalin:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports: 
      - 9000:9000
    depends_on: 
      - mysql_db
    restart: always
    environment:
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_HOST=mysql_db
      - JAVA_OPTS=-Xmx512m

  mysql_db:
    image: mysql:8.0
    ports:
      - ${MYSQL_PORT}:3306
    environment: 
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./mysql/init/database_initialize.sql:/docker-entrypoint-initdb.d/1.sql"
      - mysql_db_data:/var/lib/mysql
    
  adminer_container:
    image: adminer:latest
    environment: 
      ADMINER_DEFAULT_SERVER: mysql_db
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  mysql_db_data:
